# Generated by Django 5.2.3 on 2025-06-25 23:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The headline of the news article.', max_length=200)),
                ('slug', models.SlugField(help_text="A short label for the article, used in URLs (e.g., 'global-summit-agreement').", max_length=200, unique=True)),
                ('content', models.TextField(help_text='The full content of the news article.')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the article was published.')),
                ('image_url', models.URLField(blank=True, help_text='URL of the main image for the article. (e.g., from Placehold.co)', max_length=500, null=True)),
                ('summary', models.TextField(blank=True, help_text='A short summary of the article for list views.')),
                ('author', models.ForeignKey(blank=True, help_text='The author of this article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-publication_date'],
            },
        ),
    ]
